name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd entropy-ml-monitor || exit
            git pull origin main
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker build -t modelpulse .
            docker run -d -p 80:5000 modelpulse
